apiVersion: apps/v1
kind: Deployment
metadata:
  name: your-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: your-app
  template:
    metadata:
      labels:
        app: your-app
    spec:
      containers:
      - name: your-app
        image: smasiner2/python_time
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config-volume
          mountPath: /config.json
          subPath: config.json
          readOnly: true
      volumes:
      - name: config-volume
        configMap:
          name: myapp-config
