apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-python
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-python
  template:
    metadata:
      labels:
        app: app-python
    spec:
      containers:
      - name: app-python
        image: smasiner2/python_app:latest
        ports:
        - containerPort: 8080
        env:
          - name: TZ
            value: "Europe/Moscow"
